baseURL = "https://gaozuwei2005.github.io/"
languageCode = "zh-cn"
title = "Zuwei"
theme = "PaperMod"

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

[menu]
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 30
  [[menu.main]]
    name = "Timeline"
    url = "/timeline/"
    weight = 40 
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

[markup.goldmark.renderer]
  unsafe = true